# teste_cond_index

In [2]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt

import freqcol_0_6 as fc
import msise2Netcdf as msise
import irinetcdf_02 as iri
import pyigrf_clara_0_6 as igrf

import conductivity0_9_6 as cond

In [3]:
me = 9.109389e-31 #Mass of electron [kg]
e = -1.602177e-19 #Electron Charge [C]
mi1 = 5.065e-26 #Ion 1 mass, ion 1 being a mixture of NO+ (75%) and O2+ (25%) (30.5 u.m.a.) [kg]
mi2 = 2.657e-26 #Ion 2 mass (O+) [kg] (16 a.m.u)

In [4]:
def calc_girofreq(mi,B):
    """
    Funcao para cálculo da girofrequência ou frequência de ciclotron da
    partícula num ponto.
    
    Parameters
    ----------
    B : FLOAT
        campo magnético em [T]
    mi : FLOAT
        massa do íon ou do elétron [kg]    
    q : FLOAT
        carga do íon/elétron [C]
    
    Returns:
    ----------
    wi : FLOAT
        girofrequencia [Hz] 
    """
    e = -1.602177e-19 #Electron charge[C]
    
    wi = np.sqrt(e**2) * np.sqrt(B**2)/mi
    return wi

In [5]:
resIGRF  = "teste2024"
dado     = igrf.IGRF(-60,0,100,2008,resIGRF) #preciso garantir que estão nas mesmas coordenadas
calcigrf = dado.get_grid(resIGRF + "_grid.csv")

In [6]:
calcigrf

,Unnamed: 0,Altitude,Latitude,Longitude,Year,Declination,Inclination,Horizontal_intensity,Total_intensity,North_component,East_component,Vertical_component,DeclinationSV,InclinationSV,HorizontalSV,TotalSV,NorthSV,EastSV,VerticalSV,B(T)
0,0,100.0,-80.000001,-180.0,2008.0,130.650016,-78.987166,11153.322641,58385.533834,-7265.684471,8462.058561,-57310.330265,7.565173,23.511294,-2.036640,-55.740408,2.966179,33.745822,61.298534,0.000058
1,1,120.0,-80.000001,-180.0,2008.0,130.499818,-79.010623,11018.823173,57803.059603,-7156.126584,8378.801610,-56743.098571,7.520720,23.088675,-2.023693,-55.172748,3.003731,33.133740,60.625124,0.000058
2,2,140.0,-80.000001,-180.0,2008.0,130.350214,-79.034002,10886.398389,57228.635303,-7048.484938,8296.537227,-56183.654463,7.476869,22.674103,-2.010814,-54.612589,3.039874,32.534229,59.961390,0.000057
3,3,160.0,-80.000001,-180.0,2008.0,130.201192,-79.057301,10756.009870,56662.117176,-6942.720231,8215.253138,-55631.859349,7.433613,22.267414,-1.998004,-54.059809,3.074645,31.946992,59.307161,0.000057
4,4,180.0,-80.000001,-180.0,2008.0,130.052744,-79.080520,10627.620034,56103.364620,-6838.794111,8134.937166,-55087.577675,7.390942,21.868444,-1.985261,-53.514284,3.108079,31.371737,58.662268,0.000056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,400.0,-10.000001,-10.0,2008.0,-14.910985,-42.553076,17460.269263,23702.220866,16872.325464,-4492.842770,-16029.169387,-5.916706,-34.003484,11.901178,27.788509,-24.883302,38.087681,-79.378164,0.000024
2876,2876,420.0,-10.000001,-10.0,2008.0,-14.867875,-42.390335,17335.101817,23471.199222,16754.724287,-4448.029799,-15823.761813,-5.913473,-33.655916,11.875750,27.091216,-24.637715,37.752470,-78.289196,0.000023
2877,2877,440.0,-10.000001,-10.0,2008.0,-14.825444,-42.228767,17210.972595,23243.394867,16638.016783,-4403.859125,-15621.710127,-5.909949,-33.311545,11.850285,26.412814,-24.394139,37.419322,-77.221260,0.000023
2878,2878,460.0,-10.000001,-10.0,2008.0,-14.783677,-42.068361,17087.875149,23018.749405,16522.200275,-4360.318244,-15422.948715,-5.906145,-32.970396,11.824790,25.752726,-24.152603,37.088295,-76.173835,0.000023
2879,2879,480.0,-10.000001,-10.0,2008.0,-14.742556,-41.909108,16965.802919,22797.205720,16407.271846,-4317.394965,-15227.413436,-5.902072,-32.632492,11.799272,25.110397,-23.913138,36.759438,-75.146413,0.000023

In [7]:
dado.Dfgrid

,Unnamed: 0,Altitude,Latitude,Longitude,Year,Declination,Inclination,Horizontal_intensity,Total_intensity,North_component,East_component,Vertical_component,DeclinationSV,InclinationSV,HorizontalSV,TotalSV,NorthSV,EastSV,VerticalSV,B(T)
0,0,100.0,-80.000001,-180.0,2008.0,130.650016,-78.987166,11153.322641,58385.533834,-7265.684471,8462.058561,-57310.330265,7.565173,23.511294,-2.036640,-55.740408,2.966179,33.745822,61.298534,0.000058
1,1,120.0,-80.000001,-180.0,2008.0,130.499818,-79.010623,11018.823173,57803.059603,-7156.126584,8378.801610,-56743.098571,7.520720,23.088675,-2.023693,-55.172748,3.003731,33.133740,60.625124,0.000058
2,2,140.0,-80.000001,-180.0,2008.0,130.350214,-79.034002,10886.398389,57228.635303,-7048.484938,8296.537227,-56183.654463,7.476869,22.674103,-2.010814,-54.612589,3.039874,32.534229,59.961390,0.000057
3,3,160.0,-80.000001,-180.0,2008.0,130.201192,-79.057301,10756.009870,56662.117176,-6942.720231,8215.253138,-55631.859349,7.433613,22.267414,-1.998004,-54.059809,3.074645,31.946992,59.307161,0.000057
4,4,180.0,-80.000001,-180.0,2008.0,130.052744,-79.080520,10627.620034,56103.364620,-6838.794111,8134.937166,-55087.577675,7.390942,21.868444,-1.985261,-53.514284,3.108079,31.371737,58.662268,0.000056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,400.0,-10.000001,-10.0,2008.0,-14.910985,-42.553076,17460.269263,23702.220866,16872.325464,-4492.842770,-16029.169387,-5.916706,-34.003484,11.901178,27.788509,-24.883302,38.087681,-79.378164,0.000024
2876,2876,420.0,-10.000001,-10.0,2008.0,-14.867875,-42.390335,17335.101817,23471.199222,16754.724287,-4448.029799,-15823.761813,-5.913473,-33.655916,11.875750,27.091216,-24.637715,37.752470,-78.289196,0.000023
2877,2877,440.0,-10.000001,-10.0,2008.0,-14.825444,-42.228767,17210.972595,23243.394867,16638.016783,-4403.859125,-15621.710127,-5.909949,-33.311545,11.850285,26.412814,-24.394139,37.419322,-77.221260,0.000023
2878,2878,460.0,-10.000001,-10.0,2008.0,-14.783677,-42.068361,17087.875149,23018.749405,16522.200275,-4360.318244,-15422.948715,-5.906145,-32.970396,11.824790,25.752726,-24.152603,37.088295,-76.173835,0.000023
2879,2879,480.0,-10.000001,-10.0,2008.0,-14.742556,-41.909108,16965.802919,22797.205720,16407.271846,-4317.394965,-15227.413436,-5.902072,-32.632492,11.799272,25.110397,-23.913138,36.759438,-75.146413,0.000023

In [8]:
calcigrf["Latitude"] = np.round(calcigrf["Latitude"],5)

In [9]:
calcigrf

,Unnamed: 0,Altitude,Latitude,Longitude,Year,Declination,Inclination,Horizontal_intensity,Total_intensity,North_component,East_component,Vertical_component,DeclinationSV,InclinationSV,HorizontalSV,TotalSV,NorthSV,EastSV,VerticalSV,B(T)
0,0,100.0,-80.0,-180.0,2008.0,130.650016,-78.987166,11153.322641,58385.533834,-7265.684471,8462.058561,-57310.330265,7.565173,23.511294,-2.036640,-55.740408,2.966179,33.745822,61.298534,0.000058
1,1,120.0,-80.0,-180.0,2008.0,130.499818,-79.010623,11018.823173,57803.059603,-7156.126584,8378.801610,-56743.098571,7.520720,23.088675,-2.023693,-55.172748,3.003731,33.133740,60.625124,0.000058
2,2,140.0,-80.0,-180.0,2008.0,130.350214,-79.034002,10886.398389,57228.635303,-7048.484938,8296.537227,-56183.654463,7.476869,22.674103,-2.010814,-54.612589,3.039874,32.534229,59.961390,0.000057
3,3,160.0,-80.0,-180.0,2008.0,130.201192,-79.057301,10756.009870,56662.117176,-6942.720231,8215.253138,-55631.859349,7.433613,22.267414,-1.998004,-54.059809,3.074645,31.946992,59.307161,0.000057
4,4,180.0,-80.0,-180.0,2008.0,130.052744,-79.080520,10627.620034,56103.364620,-6838.794111,8134.937166,-55087.577675,7.390942,21.868444,-1.985261,-53.514284,3.108079,31.371737,58.662268,0.000056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,400.0,-10.0,-10.0,2008.0,-14.910985,-42.553076,17460.269263,23702.220866,16872.325464,-4492.842770,-16029.169387,-5.916706,-34.003484,11.901178,27.788509,-24.883302,38.087681,-79.378164,0.000024
2876,2876,420.0,-10.0,-10.0,2008.0,-14.867875,-42.390335,17335.101817,23471.199222,16754.724287,-4448.029799,-15823.761813,-5.913473,-33.655916,11.875750,27.091216,-24.637715,37.752470,-78.289196,0.000023
2877,2877,440.0,-10.0,-10.0,2008.0,-14.825444,-42.228767,17210.972595,23243.394867,16638.016783,-4403.859125,-15621.710127,-5.909949,-33.311545,11.850285,26.412814,-24.394139,37.419322,-77.221260,0.000023
2878,2878,460.0,-10.0,-10.0,2008.0,-14.783677,-42.068361,17087.875149,23018.749405,16522.200275,-4360.318244,-15422.948715,-5.906145,-32.970396,11.824790,25.752726,-24.152603,37.088295,-76.173835,0.000023
2879,2879,480.0,-10.0,-10.0,2008.0,-14.742556,-41.909108,16965.802919,22797.205720,16407.271846,-4317.394965,-15227.413436,-5.902072,-32.632492,11.799272,25.110397,-23.913138,36.759438,-75.146413,0.000023

In [10]:
dado.Dfgrid['Longitude'] = 180 + dado.Dfgrid['Longitude']

In [11]:
dado.Dfgrid

,Unnamed: 0,Altitude,Latitude,Longitude,Year,Declination,Inclination,Horizontal_intensity,Total_intensity,North_component,East_component,Vertical_component,DeclinationSV,InclinationSV,HorizontalSV,TotalSV,NorthSV,EastSV,VerticalSV,B(T)
0,0,100.0,-80.0,0.0,2008.0,130.650016,-78.987166,11153.322641,58385.533834,-7265.684471,8462.058561,-57310.330265,7.565173,23.511294,-2.036640,-55.740408,2.966179,33.745822,61.298534,0.000058
1,1,120.0,-80.0,0.0,2008.0,130.499818,-79.010623,11018.823173,57803.059603,-7156.126584,8378.801610,-56743.098571,7.520720,23.088675,-2.023693,-55.172748,3.003731,33.133740,60.625124,0.000058
2,2,140.0,-80.0,0.0,2008.0,130.350214,-79.034002,10886.398389,57228.635303,-7048.484938,8296.537227,-56183.654463,7.476869,22.674103,-2.010814,-54.612589,3.039874,32.534229,59.961390,0.000057
3,3,160.0,-80.0,0.0,2008.0,130.201192,-79.057301,10756.009870,56662.117176,-6942.720231,8215.253138,-55631.859349,7.433613,22.267414,-1.998004,-54.059809,3.074645,31.946992,59.307161,0.000057
4,4,180.0,-80.0,0.0,2008.0,130.052744,-79.080520,10627.620034,56103.364620,-6838.794111,8134.937166,-55087.577675,7.390942,21.868444,-1.985261,-53.514284,3.108079,31.371737,58.662268,0.000056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2875,400.0,-10.0,170.0,2008.0,-14.910985,-42.553076,17460.269263,23702.220866,16872.325464,-4492.842770,-16029.169387,-5.916706,-34.003484,11.901178,27.788509,-24.883302,38.087681,-79.378164,0.000024
2876,2876,420.0,-10.0,170.0,2008.0,-14.867875,-42.390335,17335.101817,23471.199222,16754.724287,-4448.029799,-15823.761813,-5.913473,-33.655916,11.875750,27.091216,-24.637715,37.752470,-78.289196,0.000023
2877,2877,440.0,-10.0,170.0,2008.0,-14.825444,-42.228767,17210.972595,23243.394867,16638.016783,-4403.859125,-15621.710127,-5.909949,-33.311545,11.850285,26.412814,-24.394139,37.419322,-77.221260,0.000023
2878,2878,460.0,-10.0,170.0,2008.0,-14.783677,-42.068361,17087.875149,23018.749405,16522.200275,-4360.318244,-15422.948715,-5.906145,-32.970396,11.824790,25.752726,-24.152603,37.088295,-76.173835,0.000023
2879,2879,480.0,-10.0,170.0,2008.0,-14.742556,-41.909108,16965.802919,22797.205720,16407.271846,-4317.394965,-15227.413436,-5.902072,-32.632492,11.799272,25.110397,-23.913138,36.759438,-75.146413,0.000023

In [12]:
dado.Dfgrid = dado.going_to_multiindex(dado.Dfgrid)

In [13]:
dado.Dfgrid

                             Unnamed: 0    Year  Declination  Inclination  \
Altitude Latitude Longitude
100.0    -80.0    0.0                 0  2008.0   130.650016   -78.987166
                  10.0               20  2008.0   118.156275   -78.234921
                  20.0               40  2008.0   106.832854   -77.322789
                  30.0               60  2008.0    96.522522   -76.294058
                  40.0               80  2008.0    87.026928   -75.185835
...                                 ...     ...          ...          ...
480.0    -10.0    130.0            2799  2008.0   -17.690021   -10.387168
                  140.0            2819  2008.0   -20.305179   -20.642006
                  150.0            2839  2008.0   -20.233242   -30.106123
                  160.0            2859  2008.0   -18.086164   -37.275007
                  170.0            2879  2008.0   -14.742556   -41.909108

                             Horizontal_intensity  Total_intensity  \
Altitude Latitude Longitude
100.0    -80.0    0.0                11153.322641     58385.533834
                  10.0               11796.972738     57856.827783
                  20.0               12548.832156     57180.974298
                  30.0               13357.744352     56376.322607
                  40.0               14180.630634     55461.381823
...                                           ...              ...
480.0    -10.0    130.0              19446.739985     19770.745441
                  140.0              18741.660767     20027.392637
                  150.0              17922.886216     20717.756668
                  160.0              17262.781656     21694.059118
                  170.0              16965.802919     22797.205720

                             North_component  East_component  \
Altitude Latitude Longitude
100.0    -80.0    0.0           -7265.684471     8462.058561
                  10.0          -5566.732704    10400.964032
                  20.0          -3633.899525    12011.159924
                  30.0          -1517.356497    13271.283413
                  40.0            735.501253    14161.543811
...                                      ...             ...
480.0    -10.0    130.0         18527.189545    -5909.225299
                  140.0         17577.008472    -6503.739039
                  150.0         16816.910214    -6198.498301
                  160.0         16409.840202    -5359.176713
                  170.0         16407.271846    -4317.394965

                             Vertical_component  DeclinationSV  InclinationSV  \
Altitude Latitude Longitude
100.0    -80.0    0.0             -57310.330265       7.565173      23.511294
                  10.0            -56641.362584       6.464516      22.855311
                  20.0            -55787.011330       5.615294      21.136468
                  30.0            -54770.981518       5.006495      18.564271
                  40.0            -53617.856993       4.590182      15.354725
...                                         ...            ...            ...
480.0    -10.0    130.0            -3564.642935       4.699529     -43.494612
                  140.0            -7060.212995       1.159119     -46.069407
                  150.0           -10392.092717      -1.787924     -45.017671
                  160.0           -13138.819220      -3.885176     -38.961981
                  170.0           -15227.413436      -5.902072     -32.632492

                             HorizontalSV    TotalSV    NorthSV     EastSV  \
Altitude Latitude Longitude
100.0    -80.0    0.0           -2.036640 -55.740408   2.966179  33.745822
                  10.0          -2.118941 -60.270817   8.488085  30.605751
                  20.0          -2.159970 -64.558690  13.271634  26.201494
                  30.0          -2.166299 -68.446613  17.047840  20.719015
                  40.0          -2.143847 -71.804833  19.586268  14.433508
...                                   ...        ...        ...        ...
480.0    -10.0    130.0         19.884073 -25.106721 -49.519087 -12.485058
                  140.0         20.423865  -6.459802 -45.425787   9.970532
                  150.0         17.992148   8.957860 -38.953328  24.442432
                  160.0         14.723561  20.163238 -30.834041  30.872129
                  170.0         11.799272  25.110397 -23.913138  36.759438

                             VerticalSV      B(T)
Altitude Latitude Longitude
100.0    -80.0    0.0         61.298534  0.000058
                  10.0        66.256354  0.000058
                  20.0        70.856212  0.000057
                  30.0        74.910469  0.000056
                  40.0        78.266974  0.000055
...                                 ...       ...
480.0    -10.0    130.0     -109.138550  0.000020
                  140.0     -109.997336  0.000020
                  150.0      -98.881026  0.000021
                  160.0      -86.440298  0.000022
                  170.0      -75.146413  0.000023

[2880 rows x 17 columns]

# Calculando girofrequência angular

In [15]:
def calc_all_girofreq(B):
        me = 9.109389e-31 #Massa do elétron em repouso [kg]
        e = -1.602177e-19 #Carga do elétron [C]
        mi1 = 5.065e-26 #Massa do íon 1 uma mistura de NO+ (75%) e O2+ (25%) (30.5 u.m.a.) [kg]
        mi2 = 2.657e-26 #Massa do íon 2 (O+) [kg] (16 a.m.u)
        
        print("\nCalculating all Girofrequencies...")
        wi1 = calc_girofreq(mi1, B)
        wi2 = calc_girofreq(mi2, B)
        we = calc_girofreq(me, B)
        #print("\n\ncondiono_adachi calc_all_girofreq  wi1: ",wi1,"\nwi2:",wi2,"\nwe5:",we)
       # print('lon: ',long,'lat: ',lat)
        
        agirofreq = pd.concat([we,wi1,wi2], axis = 1, keys = ["we","wi1","wi2"],join='inner')
            
        print("Done")
        return agirofreq

In [16]:
we = calc_girofreq(me,dado.Dfgrid["B(T)"])
we

Altitude  Latitude  Longitude
100.0     -80.0     0.0          1.026896e+07
                    10.0         1.017597e+07
                    20.0         1.005710e+07
                    30.0         9.915577e+06
                    40.0         9.754655e+06
                                     ...
480.0     -10.0     130.0        3.477317e+06
                    140.0        3.522457e+06
                    150.0        3.643879e+06
                    160.0        3.815593e+06
                    170.0        4.009617e+06
Name: B(T), Length: 2880, dtype: float64

In [17]:
wi1 = calc_girofreq(mi1,dado.Dfgrid["B(T)"])
wi2 = calc_girofreq(mi2,dado.Dfgrid["B(T)"])
wi1,'\n',wi2

(Altitude  Latitude  Longitude
 100.0     -80.0     0.0          184.686988
                     10.0         183.014568
                     20.0         180.876687
                     30.0         178.331387
                     40.0         175.437217
                                     ...
 480.0     -10.0     130.0         62.539454
                     140.0         63.351289
                     150.0         65.535071
                     160.0         68.623342
                     170.0         72.112850
 Name: B(T), Length: 2880, dtype: float64,
 '\n',
 Altitude  Latitude  Longitude
 100.0     -80.0     0.0          352.066087
                     10.0         348.877978
                     20.0         344.802566
                     30.0         339.950498
                     40.0         334.433385
                                     ...
 480.0     -10.0     130.0        119.218041
                     140.0        120.765630
                     150.0        124.928541
                     160.0        130.815666
                     170.0        137.467665
 Name: B(T), Length: 2880, dtype: float64)

In [18]:
gyr = calc_all_girofreq(dado.Dfgrid["B(T)"])

Calculating all Girofrequencies...
Done

In [19]:
gyr.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2880 entries, (100.0, -80.0, 0.0) to (480.0, -10.0, 170.0)
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   we      2880 non-null   float64
 1   wi1     2880 non-null   float64
 2   wi2     2880 non-null   float64
dtypes: float64(3)
memory usage: 77.8 KB

# Frequência de colisão

## Lendo modelos 
### IRI

In [22]:
namefileiri = "IRI.3D.2008001.nc"
iriteste = iri.irincdf(namefileiri)

Separating the results for a specific day in order to work with less data.

### NRLMSISE 2

In [25]:
filenamemsise2 = "NRLMSIS2.0.3D.2008001.nc"
msisetest = msise.nrlmsisenetcdf(filenamemsise2)

In [26]:
msisetest.msise.data['N2'].loc['0 days 00:00:00']

ht     lat    lon
0.0    -90.0  0.0      1.210602e+25
              20.0     1.210602e+25
              40.0     1.210602e+25
              60.0     1.210602e+25
              80.0     1.210602e+25
                           ...
500.0   90.0  280.0    1.627130e+09
              300.0    1.627130e+09
              320.0    1.627130e+09
              340.0    1.627130e+09
              360.0    1.627130e+09
Name: N2, Length: 71003, dtype: float64

In [27]:
msisetest.msise.data['N2']

time             ht     lat    lon
0 days 00:00:00  0.0    -90.0  0.0      1.210602e+25
                               20.0     1.210602e+25
                               40.0     1.210602e+25
                               60.0     1.210602e+25
                               80.0     1.210602e+25
                                            ...
0 days 23:45:00  500.0   90.0  280.0    1.627130e+09
                               300.0    1.627130e+09
                               320.0    1.627130e+09
                               340.0    1.627130e+09
                               360.0    1.627130e+09
Name: N2, Length: 6816288, dtype: float64

# Calculating the collision frequencies

In [29]:
freqc = fc.freqcol(msisetest.msise["N2"].data["N2"].loc['0 days 00:00:00'],
            msisetest.msise["O2"].data["O2"].loc['0 days 00:00:00'],
            msisetest.msise["O"].data["O"].loc['0 days 00:00:00'],
            iriteste.iridata['Te'].data['Te'].loc['0 days 00:00:00'],
            iriteste.iridata['Tn'].data['Tn'].loc['0 days 00:00:00'],
            iriteste.iridata['Ti'].data['Ti'].loc['0 days 00:00:00'])

TypeError: 'basencdf' object is not subscriptable

In [ ]:
freqc.resul.index().unique

In [ ]:
freqc.resul

# Testing Halls conductivity

In [ ]:
gyr.join(freqc.resul["ion1"])

In [ ]:
gyr.loc[:,"ion2"] = freqc.resul["ion2"]

In [ ]:
gyr["ion2"]

In [ ]:
 a1 = gyr['wi2']**2/(gyr['wi2']**2 + gyr["ion2"]**2)

In [ ]:
a1